namespaces: rabbitmq

traefik:
  ingress:
    routes:
      - kind: Rule
        match: Host(`istanbul.guven.uk`) && PathPrefix(`/rabbit`)
        services:
          - name: rabbitmq
            port: 15672
            
  ingressTCP:
    routes:
      - match: HostSNI(`*`)
        services:
          - name: rabbitmq
            port: 5672