# Default values for rabbitmq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: rabbitmq
namespace: rabbitmq
replicaCount: 3


image:
  repository: rabbitmq
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.8"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount: {}
podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  name: rabbitmq
  type: ClusterIP
  ports:
    - name: http
      port: 15672
      targetPort: 15672
      protocol: TCP
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
 limits:
   cpu: '2'
   memory: 4Gi
 requests:
   cpu: '1'
   memory: 3Gi
   
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

containers:
  readinessProbe:
    exec:
      command:
        - rabbitmq-diagnostics
        - ping
    initialDelaySeconds: 20
    timeoutSeconds: 60
    periodSeconds: 60
    successThreshold: 1
    failureThreshold: 3
  livenessProbe:
    exec:
      command:
        - rabbitmq-diagnostics
        - status
    initialDelaySeconds: 20
    timeoutSeconds: 60
    periodSeconds: 60
    successThreshold: 1
    failureThreshold: 3
  env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: RABBITMQ_DEFAULT_USER
      valueFrom:
        secretKeyRef:
          name: rabbitmq
          key: username
    - name: RABBITMQ_DEFAULT_PASS
      valueFrom:
        secretKeyRef:
          name: rabbitmq
          key: password
    - name: RABBITMQ_USE_LONGNAME
      value: "true"
    - name: K8S_SERVICE_NAME
      value: rabbitmq
    - name: RABBITMQ_NODENAME
      value: "rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local"
    - name: K8S_HOSTNAME_SUFFIX
      value: .$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local
    - name: RABBITMQ_ERLANG_COOKIE
      value: mycookie  
  ports:
    - name: mngmt
      containerPort: 15672
      protocol: TCP
    - name: amqp
      containerPort: 5672
      protocol: TCP
  volumeMounts:
    - name: config-volume
      mountPath: /etc/rabbitmq
        
volumes:
  - name: config-volume
    configMap:
      name: rabbitmq
      items:
        - key: rabbitmq.conf
          path: rabbitmq.conf
        - key: enabled_plugins
          path: enabled_plugins
  - name: erlang-cookie
    secret:
      secretName: erlang-cookie-secret