apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-nginx
        image: busybox
        command: ['sh', '-c', 'echo "$(cat /mnt/index.html | sed -e "s/{{ .ClusterName }}/$(CLUSTER_NAME)/" -e "s/{{ .NodeName }}/$(NODE_NAME)/" -e "s/{{ .PodIP }}/$(POD_IP)/")" > /usr/share/nginx/html/index.html']
        env:
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: cluster-info
              key: cluster-name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: index-html
          mountPath: /mnt
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: index-html
        configMap:
          name: nginx-index
      - name: nginx-html
        emptyDir: {}
