apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>NGINX</title>
      <style>
        body {
          font-size: 18px;
        }
      </style>
    </head>
    <body>
      <h1>Welcome to NGINX!</h1>
      <p>Cluster Name: {{ .ClusterName }}</p>
      <p>Worker Node: {{ .NodeName }}</p>
      <p>Pod IP: {{ .PodIP }}</p>
    </body>
    </html>
