apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-hazelcast
  namespace: hazelcast
spec:
  stripPrefix:
    prefixes:
      - "/hazelcast"
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.appName }}-mancenter
  annotations: 
    kubernetes.io/ingress.class: traefik-external 
spec:
  entryPoints:
    - websecure
  routes:  
    {{- toYaml .Values.traefik.ingress.routes | nindent 20 }} 
