apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-grafana
  namespace: loki-stack
spec:
  stripPrefix:
    prefixes:
      - "/grafana"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-dashboard
  namespace: loki-stack
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:  
    - match: |
            {{- if eq .Release.Name "loki-stack-izmir" -}}
            Host(`{{ .Values.instances.loki-stack-izmir.host }}`) && PathPrefix(`grafana`)
            {{- else if eq .Release.Name "loki-stack-istanbul" -}}
            Host(`{{ .Values.instances.loki-stack-istanbul.host }}`) && PathPrefix(`grafana`)
            {{- end }}
      kind: Rule
      services:
        - name: |
            {{- if eq .Release.Name "loki-stack-izmir" -}}
            {{ .Values.instances.loki-stack-izmir.serviceName }}
            {{- else if eq .Release.Name "loki-stack-istanbul" -}}
            {{ .Values.instances.loki-stack-istanbul.serviceName }}
            {{- end }}
          port: 80
      middlewares:
        - name: strip-grafana
          namespace: loki-stack