apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-grafana
  namespace: loki-stack
spec:
  stripPrefix:
    prefixes:
      - "/grafana"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-dashboard
  namespace: loki-stack
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}  
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: |
        {{- if contains "izmir" .Release.Name }}
        Host(`{{ .Values.instances.izmir.host }}`) && PathPrefix(`/grafana`)
        {{- else if contains "istanbul" .Release.Name }}
        Host(`{{ .Values.instances.istanbul.host }}`) && PathPrefix(`/grafana`)
        {{- else }}
        Host(`default.guven.uk`) && PathPrefix(`/grafana`)
        {{- end }}
      kind: Rule
      services:
        port: 80
        namespace: loki-stack      
        - name: |
            {{- if contains "izmir" .Release.Name }}
            {{ .Values.instances.izmir.serviceName }}
            {{- else if contains "istanbul" .Release.Name }}
            {{ .Values.instances.istanbul.serviceName }}
            {{- end }}
      middlewares:
        namespace: loki-stack
        - name: strip-grafana
          