apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
      daemon
      maxconn 500

    defaults
      mode tcp
      log global
      timeout connect 360s
      timeout client 600s
      timeout server 600s
      timeout check 60s

    frontend http
      bind :8080
      default_backend stats

    backend stats
      mode http
      stats enable
      stats uri /
      stats refresh 1s
      stats show-legends
      stats admin if TRUE

    resolvers kubedns
      nameserver namesrv1 kube-dns.kube-system.svc.cluster.local:53
      resolve_retries  3
      timeout retry 3s
      hold other 10s
      hold refused 10s
      hold nx 10s
      hold timeout 10s
      hold valid 10s
      hold obsolete 10s

    frontend redis-read
      bind *:6380
      default_backend redis-online

    frontend redis-write
      bind *:6379
      default_backend redis-primary

    backend redis-primary
      mode tcp
      balance first
      option tcp-check
      tcp-check send AUTH\ {{ .Values.password }}\r\n
      tcp-check expect string +OK
      tcp-check send PING\r\n
      tcp-check expect string +PONG
      tcp-check send info\ replication\r\n
      tcp-check expect string role:master
      tcp-check send QUIT\r\n
      tcp-check expect string +OK
      default-server  check resolvers kubedns inter 1s downinter 1s fastinter 1s fall 1 rise 3 maxconn 330 no-agent-check on-error mark-down
      server redis-0 redis-0.{{ .Values.appName }}.{{ .Values.namespace }}.svc.cluster.local:6379
      server redis-1 redis-1.{{ .Values.appName }}.{{ .Values.namespace }}.svc.cluster.local:6379
      server redis-2 redis-2.{{ .Values.appName }}.{{ .Values.namespace }}.svc.cluster.local:6379
      

    backend redis-online
      mode tcp
      balance roundrobin
      option tcp-check
      tcp-check send AUTH\ {{ .Values.password }}\r\n
      tcp-check expect string +OK
      tcp-check send PING\r\n
      tcp-check expect string +PONG
      tcp-check send QUIT\r\n
      tcp-check expect string +OK
      default-server  check resolvers kubedns inter 1s downinter 1s fastinter 1s fall 1 rise 3 maxconn 330 no-agent-check on-error mark-down
      server redis-0 redis-0.{{ .Values.appName }}.{{ .Values.namespace }}.svc.cluster.local:6379
      server redis-1 redis-1.{{ .Values.appName }}.{{ .Values.namespace }}.svc.cluster.local:6379
      server redis-2 redis-2.{{ .Values.appName }}.{{ .Values.namespace }}.svc.cluster.local:6379
      
      

