kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-pvc" (include "redis.fullname" .) }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
  volumeMode: Filesystem