namespaces: ollama

traefik:
  ingress:
    routes:
      - kind: Rule
        match: Host(`izmir.guven.uk`) && PathPrefix(`/ollama`)
        services:
          - name: ollama
            port: 11434
          