apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Values.appName}}
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - loki
  routes:
    {{- toYaml .Values.traefik.loki.ingress.routes | nindent 10 }}