namespaces: hazelcast

traefik:
  ingress:
    routes:
      - kind: Rule
        match: Host(`istanbul.guven.uk`) && PathPrefix(`/hazelcast`)
        services:
          - name: hazelcast-istanbul-mancenter
            port: 8080
        middlewares:
          - name: strip-hazelcast
            namespace: hazelcast   
          - name: add-x-forwarded-proto
            namespace: hazelcast                                
            
  ingressTCP:
    routes:
      - match: HostSNI(`*`)
        services:
          - name: hazelcast-istanbul
            port: 5701
       