namespaces: hazelcast

traefik:
  ingress:
    routes:
      - kind: Rule
        match: Host(`hazelcast.guven.uk`)
        services:
          - name: hazelcast-istanbul-mancenter
            port: 8080
            
  ingressTCP:
    routes:
      - match: HostSNI(`*`)
        services:
          - name: hazelcast-istanbul
            port: 5701
       