namespaces: hazelcast

traefik:
  ingress:
    routes:
      - kind: Rule
        match: Host(`izmir.guven.uk`) && PathPrefix(`/hazelcast`)
        services:
          - name: hazelcast-izmir-mancenter
            port: 8080
            
  ingressTCP:
    routes:
      - match: HostSNI(`*`)
        services:
          - name: hazelcast-izmir
            port: 5701