namespaces: hazelcast

traefik:
  # ingress:
  #   routes:
  #     - kind: Rule
  #       match: Host(`izmir.guven.uk`) && PathPrefix(`/hazelcast`)
  #       services:
  #         - name: hz-hazelcast-mancenter
  #           port: 9443
            
  ingressTCP:
    routes:
      - match: HostSNI(`*`)
        services:
          - name: hz-hazelcast
            port: 5701