apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ollama-ingress
  annotations: 
    kubernetes.io/ingress.class: traefik-external 
spec:
  entryPoints:
    - websecure
  routes:  
    {{- toYaml .Values.traefik.ingress.routes | nindent 20 }} 

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ollama-strip-prefix
  namespace: ollama
spec:
  stripPrefix:
    prefixes:
      - "/ollama"
