# nindent 20
traefik:
  redis:
    ingress:
      routes:
        - match: HostSNI(`*`)
          services:
            - name: redis-haproxy
              port: 6379
              terminationDelay: 60000        
              nativeLB: true

  haproxy:
    ingress:
      routes:
        - kind: Rule
          match: Host(`istanbul.guven.uk`) && PathPrefix(`/redisui`)
          services:
            - name: redis-haproxy
              port: 8080     