# nindent 20
traefik:
  redis:
    ingress:
      routes:
        - match: HostSNI(`*`)
          services:
            - name: redis-haproxy-write
              port: 6379
              terminationDelay: 60000        
              nativeLB: true

  haproxy:
    ingress:
      routes:
        - kind: Rule
          match: Host(`redis-haproxy-izmir.guven.uk`)
          services:
            - name: redis-haproxy-dashboard
              port: 8080     