apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres
  annotations: 
    kubernetes.io/ingress.class: traefik-external 
spec:
  entryPoints:
    - postgres
  routes:  
    {{- toYaml .Values.traefik.ingressTCP.routes | nindent 10 }}
    