apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  namespace: traefik
spec:
  secretName: traefik-ca-secret
  issuerRef:
    name: traefik-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - api.rsm-dev-cloud.vodafone.local
    - argocd.rsm-dev-cloud.vodafone.local
    - rancher.rsm-dev-cloud.vodafone.local
    - longhorn.rsm-dev-cloud.vodafone.local
    - grafana.rsm-dev-cloud.vodafone.local