apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app:  {{ .Chart.Name }}
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 10 }}
  selector:
    app:  {{ .Chart.Name }}
